### ISSUE TITLE
Home

### ISSUE THREAD

**Issue by 3lm0n0** [belenkestingDurand/grupo_4_entrelineas#1]
Deberia estar el html y algo de css del home.

**Comment by gagomanuel** [comment]
Ya esta empezado el home, y tambien agregue un poco de css

**Comment by 3lm0n0** [comment]
Genial

**Comment by 3lm0n0** [comment]
no deberian cerrar las issues sin el consentimiento del que la abre

**Comment by gagomanuel** [comment]
Perdon, pense que era del grupo y lo hice rápidamente
